spring:
  security:
    enabled: false
    basic:
      enabled: false
  data:
    mongodb:
      uri: mongodb+srv://adriantournour:epfDtL7TnzdAaPbr@poo2025.qms4uoq.mongodb.net/?retryWrites=true&w=majority&appName=POO2025
      database: POO2025
  messages:
    basename: messages
    encoding: UTF-8

logging:
  level:
    root: info
management:
  security:
    enabled: false
  endpoints:
    enabled-by-default: false
    web:
      base-path: /metrics
      exposure:
        include: "health,info"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
       
poo:
  exceptions:
    code-prefix: 'UADER-POO'
  cors:
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
    allowed-headers: "*"
    max-age: 3600
  
server:
  port :  ${CONECTOR_PORT:9001}
  servlet:
    contextPath: /poo
